version: '3.7'

services: 
    web: 
        build: .
        command: python /projects/manage.py runserver 0.0.0:8000
        volumes: 
            - .:/projects
        ports:
            - 8000:8000
        depends_on: 
            - db 
        environment: 
            - SECRET_KEY=k+b+5gk-nfb#6%_h6@xsz30z!(qrp%sdxfc2($$mhkrgsl!+m(e
            - DEBUG=1
    db: 
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
volumes: 
    postgres_data: